CircleApp.UI/Controllers/HomeController.cs
namespace CircleApp.UI.Controllers;

using System.Security.Claims;
using Base;
using Domain.Entities;
using Domain.ViewModels.Home;
using Infrastructure.Persistence.DbContexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;


[Authorize]
public class HomeController : BaseController {

    private readonly AppDbContext _appDbContext;

    private readonly ILogger<HomeController> _logger;

    private readonly IPostService _postService;

    public int LoggedInUserId { get; set; }

    public HomeController(ILogger<HomeController> logger, AppDbContext appDbContext, IPostService postService)
    {
        _postService = postService;
        _logger = logger;
        _appDbContext = appDbContext;
    }

    public async Task<IActionResult> Index()
    {
        LoggedInUserId = GetUserId();
        List<Post>? posts = await _postService.GetAllPosts(LoggedInUserId)!;

        return View(posts);
    }

    public async Task<IActionResult> Details(int postId)
    {
        var post = await _postService.GetPostByIdAsync(postId);

        return View("Details", post);
    }

    [HttpPost]
    public async Task<IActionResult> CreateStatus(PostVM post)
    {
        LoggedInUserId = GetUserId();
        await _postService.CreatePost(post, LoggedInUserId);


        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> LikePost(LikePostVm likePost)
    {
        LoggedInUserId = GetUserId();
        await _postService.LikePost(LoggedInUserId, likePost.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> AddComment(CommentPostVm commentPostVm)
    {
        LoggedInUserId = GetUserId();

        var comment = new Comment
        {
            PostId = commentPostVm.PostId,
            UserId = LoggedInUserId,
            Content = commentPostVm.Content,
            DateCreated = DateTime.UtcNow,
            DateUpdated = DateTime.UtcNow
        };

        await _postService.AddComment(comment);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteComment(DeleteCommentVm deleteCommentVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.DeleteComment(LoggedInUserId, deleteCommentVm.CommentId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> BookmarkPost(BookmarkPostVm bookmarkPostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.BookmarkPost(LoggedInUserId, bookmarkPostVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> PostVisibility(PostVisibilityVm postVisibilityVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.TogglePostVisibility(LoggedInUserId, postVisibilityVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> ReportPost(ReportPostVm reportPostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.ReportPost(LoggedInUserId, reportPostVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> DeletePost(DeletePostVm deletePostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.DeletePost(LoggedInUserId, deletePostVm.PostId);

        return RedirectToAction("Index");
    }

}

CircleApp.UI/ViewComponents/HashtagsViewComponent.cs
namespace CircleApp.UI.ViewComponents;

using Domain.Entities;
using Infrastructure.Persistence.DbContexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


public class HashtagsViewComponent : ViewComponent {

    private readonly AppDbContext _appDbContext;

    public HashtagsViewComponent(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        List<Post>? posts = ViewData["posts"] as List<Post>;
        List<int>? postIds = posts.Select(p => p.PostId).ToList();
        var oneWeekAgoNow = DateTime.UtcNow.AddDays(-7);

        List<Hashtag>? top3Hashtags = await _appDbContext.Hashtags
            .Where(h => h.DateCreated >= oneWeekAgoNow && h.Posts.Any(p => postIds.Contains(p.PostId)) && h.Count > 0)
            .OrderByDescending(n => n.Count)
            .Distinct()
            .Take(3)
            .ToListAsync();


        return View(top3Hashtags);
    }

}

CircleApp.UI/ViewComponents/StoriesViewComponent.cs
namespace CircleApp.UI.ViewComponents;

using Domain.Entities;
using Infrastructure.Persistence.DbContexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


public class StoriesViewComponent : ViewComponent {

    private readonly AppDbContext _appDbContext;

    public StoriesViewComponent(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public int LoggedInUserId { get; set; } = 1;

    public async Task<IViewComponentResult> InvokeAsync()
    {
        List<Story>? allStories = await _appDbContext.Stories
            .Where(s => !s.IsDeleted && (s.UserId == LoggedInUserId || !s.IsPrivate))
            .Include(s => s.User)
            .Include(s => s.Likes)
            .OrderByDescending(s => s.DateCreated)
            .ToListAsync();

        return View(allStories);
    }

}

CircleApp.UI/Views/Home/Index.cshtml
@model List<Post>
@{
    ViewData["Title"] = "Home Page";
    ViewBag.Posts = Model;
}

<main id="site__main" class="2xl:ml-[--w-side]  xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">

    <div class="lg:flex 2xl:gap-16 gap-12 max-w-[1065px] mx-auto" id="js-oversized">

        @* post and stories  *@
        <div class="max-w-[680px] mx-auto">

            @* stories *@
            @await Component.InvokeAsync("Stories")
            @* posts  *@
            <partial name="Home/_Post" model="Model"/>

        </div>
        @* sidebar suggested friends  *@
        <div class="flex-1">
            <div class="lg:space-y-4 lg:pb-8 max-lg:grid sm:grid-cols-2 max-lg:gap-6">
                <div class="box p-5 px-6">
                    <partial name="Sidebar/_SuggestedFriends"></partial>
                </div>
                <div class="box p-5 px-6 border1">
                    @await Component.InvokeAsync("Hashtags")
                </div>
            </div>
        </div>

    </div>

</main>

<partial name="Modals/_CreateStory" model="new CreateStoryVm()"></partial>
<partial name="Modals/_CreateStatus" model="new PostVM()"></partial>
<partial name="Home/_DeletePostConfirmation"/>
<script>
    function openPostDeleteConfirmation(postId) {
        console.log("bardiiya")
        UIkit.dropdown('.post-options-dropdown').hide();
        console.log(postId)
        document.getElementById('deleteConfirmationPostId').value = postId;
        UIkit.modal('#postDeleteDialog').show();
    }


</script>