CircleApp.UI/Controllers/FavoritesController.cs
namespace CircleApp.UI.Controllers;

using System.Security.Claims;
using Base;
using Domain.Entities;
using Domain.ViewModels.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;


[Authorize]
public class FavoritesController : BaseController {

    private readonly IFavoritesService _favoritesService;

    private readonly IPostService _postService;

    public int LoggedInUserId { get; set; }


    public FavoritesController(IFavoritesService favoritesService, IPostService postService)
    {
        _favoritesService = favoritesService;
        _postService = postService;
    }


    public async Task<IActionResult> Index()
    {
        LoggedInUserId = GetUserId();
        List<Post> bookmarkedPosts = await _favoritesService.GetFavoritePostsAsync(LoggedInUserId);

        return View(bookmarkedPosts);
    }

    [HttpPost]
    public async Task<IActionResult> CreateStatus(PostVM post)
    {
        LoggedInUserId = GetUserId();
        await _postService.CreatePost(post, LoggedInUserId);


        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> LikePost(LikePostVm likePost)
    {
        LoggedInUserId = GetUserId();
        await _postService.LikePost(LoggedInUserId, likePost.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> AddComment(CommentPostVm commentPostVm)
    {
        LoggedInUserId = GetUserId();

        var comment = new Comment
        {
            PostId = commentPostVm.PostId,
            UserId = LoggedInUserId,
            Content = commentPostVm.Content,
            DateCreated = DateTime.UtcNow,
            DateUpdated = DateTime.UtcNow
        };

        await _postService.AddComment(comment);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteComment(DeleteCommentVm deleteCommentVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.DeleteComment(LoggedInUserId, deleteCommentVm.CommentId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> BookmarkPost(BookmarkPostVm bookmarkPostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.BookmarkPost(LoggedInUserId, bookmarkPostVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> PostVisibility(PostVisibilityVm postVisibilityVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.TogglePostVisibility(LoggedInUserId, postVisibilityVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> ReportPost(ReportPostVm reportPostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.ReportPost(LoggedInUserId, reportPostVm.PostId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> DeletePost(DeletePostVm deletePostVm)
    {
        LoggedInUserId = GetUserId();
        await _postService.DeletePost(LoggedInUserId, deletePostVm.PostId);

        return RedirectToAction("Index");
    }

}

CircleApp.UI/Controllers/SettingsController.cs
namespace CircleApp.UI.Controllers;

using Base;
using Domain.Entities;
using Domain.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;


[Authorize]
public class SettingsController : BaseController {

    private readonly IUserService _userService;

    private readonly UserManager<User> _userManager;

    public SettingsController(IUserService userService, UserManager<User> userManager)
    {
        _userManager = userManager;
        _userService = userService;
    }

    public int LoggedUserId { get; set; }

    public async Task<IActionResult> Index()
    {
        var loggedInUser = await _userManager.GetUserAsync(User);

        return View(loggedInUser);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateUserProfilePicture(UpdateUserPictureVm updateUserPictureVm)
    {
        LoggedUserId = GetUserId();

        if (updateUserPictureVm.ProfilePictureImage == null) return RedirectToAction("Index");

        if (updateUserPictureVm.ProfilePictureImage.Length > 0){
            var rootFoder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");

            if (updateUserPictureVm.ProfilePictureImage.ContentType.Contains("image")){
                var rootImageFolderPath = Path.Combine(rootFoder, "profile-pictures");
                Directory.CreateDirectory(rootImageFolderPath);
                var fileName = Guid.NewGuid() + Path.GetExtension(updateUserPictureVm.ProfilePictureImage.FileName);
                var filePath = Path.Combine(rootImageFolderPath, fileName);

                await using (var stream = new FileStream(filePath, FileMode.Create)){
                    await updateUserPictureVm.ProfilePictureImage.CopyToAsync(stream);
                }

                var newPath = "/profile-pictures/" + fileName;
                await _userService.UpdateUserProfilePicture(LoggedUserId, newPath);
            }
        }

        return RedirectToAction("Index");
    }

}

CircleApp.UI/Views/Shared/Navigation/_SideBar.cshtml
<div id="site__sidebar"
     class="fixed top-0 left-0 z-[99] pt-[--m-top] overflow-hidden transition-transform xl:duration-500 max-xl:w-full max-xl:-translate-x-full">
    <div
            class="p-2 max-xl:bg-white shadow-sm 2xl:w-72 sm:w-64 w-[80%] h-[calc(100vh-64px)] relative z-30 max-lg:border-r dark:max-xl:!bg-slate-700 dark:border-slate-700">

        <div class="pr-4 border-r" data-simplebar>
            <nav id="side">
                <ul>
                    <li>
                        <a>
                            <img src="~/images/icons/home.png" class="w-6"/>
                            <span> Feed </span>
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Favorites">
                            <img src="~/images/icons/page.png" class="w-6"/>
                            <span> Favorites </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <img src="~/images/icons/group-2.png" class="w-6"/>
                            <span> Friends </span>
                        </a>
                    </li>
                </ul>
            </nav>
            <nav id="side" class="font-medium text-sm text-black border-t pt-3 mt-2">
                <div class="px-3 pb-2 text-sm font-medium">
                    <div class="text-black">Pages</div>
                </div>

                <ul class="mt-2 -space-y-2">
                    <li>
                        <a asp-controller="Settings" asp-action="Index">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                 stroke="currentColor" class="w-4 h-4">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z"/>
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                            </svg>
                            <span>Settings</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

    </div>
    <div id="site__sidebar__overly"
         class="absolute top-0 left-0 z-20 w-screen h-screen xl:hidden backdrop-blur-sm"
         uk-toggle="target: #site__sidebar ; cls :!-translate-x-0"></div>
</div>

CircleApp.UI/Views/Shared/Navigation/_TopBar.cshtml
@{
    var username = User.Identity.Name;
    var fullName = User.Claims.FirstOrDefault(c => c.Type == "FullName")?.Value;
}
<header
        class="z-[100] h-[--m-top] fixed top-0 left-0 w-full flex items-center bg-white/80 sky-50 backdrop-blur-xl border-b border-slate-200">
    <div class="2xl:w-[--w-side] lg:w-[--w-side-sm] flex justify-center">
        <div class="flex items-center justify-center gap-1">
            @* <button uk-toggle="target: #site__sidebar ; cls :!-translate-x-0" *@
            @*         class="flex items-center justify-center w-8 h-8 text-xl rounded-full hover:bg-gray-100 xl:hidden group"> *@
            @*     <ion-icon name="menu-outline" class="text-2xl group-aria-expanded:hidden"></ion-icon> *@
            @*     <ion-icon name="close-outline" class="hidden text-2xl group-aria-expanded:block"></ion-icon> *@
            @* </button> *@

            <div id="logo" class="flex items-center">
                <a class="flex items-center gap-7" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" class="w-10 md:block hidden"/>
                    <span class="ml-2">Circle App</span>
                </a>
            </div>

        </div>
    </div>
    <div class="flex-1 relative">
        <div class="max-w-[1220px] mx-auto flex items-center">
            <form id="search--box"
                  class="xl:w-[680px] sm:w-96 sm:relative rounded-xl overflow-hidden z-20 bg-secondery max-md:hidden w-screen left-0 max-sm:fixed max-sm:top-2">

                <ion-icon name="search" class="absolute left-4 top-1/2 -translate-y-1/2"></ion-icon>
                <input type="text" name="query" placeholder="Search Posts, Friends..."
                       class="w-full !pl-10 !font-normal !bg-transparent h-12 !text-sm"/>
            </form>
        </div>

        <div class="max-w-[1220px] mx-auto flex items-center">
            <div class="flex items-center sm:gap-4 gap-2 absolute right-5 top-1/2 -translate-y-1/2 text-black">

                @* notification icon *@
                <button type="button" class="sm:p-2 p-1 rounded-full relative sm:bg-secondery">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                         class="w-6 h-6 max-sm:hidden">
                        <path
                                d="M5.85 3.5a.75.75 0 00-1.117-1 9.719 9.719 0 00-2.348 4.876.75.75 0 001.479.248A8.219 8.219 0 015.85 3.5zM19.267 2.5a.75.75 0 10-1.118 1 8.22 8.22 0 011.987 4.124.75.75 0 001.48-.248A9.72 9.72 0 0019.266 2.5z"/>
                        <path fill-rule="evenodd"
                              d="M12 2.25A6.75 6.75 0 005.25 9v.75a8.217 8.217 0 01-2.119 5.52.75.75 0 00.298 1.206c1.544.57 3.16.99 4.831 1.243a3.75 3.75 0 107.48 0 24.583 24.583 0 004.83-1.244.75.75 0 00.298-1.205 8.217 8.217 0 01-2.118-5.52V9A6.75 6.75 0 0012 2.25zM9.75 18c0-.034 0-.067.002-.1a25.05 25.05 0 004.496 0l.002.1a2.25 2.25 0 11-4.5 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    <div class="absolute top-0 right-0 -m-1 bg-red-600 text-white text-xs px-1 rounded-full"
                         id="notificationsCount">0
                    </div>
                </button>

                <div class="hidden bg-white pr-1.5 rounded-lg drop-shadow-xl md:w-[365px] w-screen border2"
                     uk-drop="offset:6;pos: bottom-right; mode: click; animate-out: true;">

                    <div class="flex items-center justify-between gap-2 p-4 pb-2">
                        <h3 class="font-bold text-xl">Notifications</h3>
                    </div>

                    <div class="text-sm h-[400px] w-full overflow-y-auto pr-2">
                        <div class="pl-2 p-1 text-sm font-normal" id="notification-dropdown">
                            No notifications...
                        </div>
                    </div>

                </div>

                <div class="rounded-full relative bg-secondery cursor-pointer shrink-0">
                    <img src="~/images/avatar/user.png" class="sm:w-9 sm:h-9 w-7 h-7 rounded-full shadow shrink-0"/>
                </div>
                <div class="hidden bg-white rounded-lg drop-shadow-xl w-64 border2"
                     uk-drop="offset:6;pos: bottom-right;animate-out: true;">

                    <a>
                        <div class="p-4 py-5 flex items-center gap-4">
                            <img src="~/images/avatar/user.png" class="w-10 h-10 rounded-full shadow"/>
                            <div class="flex-1">
                                <h4 class="text-sm font-medium text-black">@fullName</h4>
                                <div class="text-sm mt-1 text-blue-600 font-light/70">@username</div>
                            </div>
                        </div>
                    </a>
                    <hr/>
                    <nav>
                        <a asp-controller="Settings" asp-action="Index">
                            <div class="flex items-center gap-2.5 hover:bg-secondery p-2 px-2.5 rounded-md">
                                <ion-icon name="settings-outline" class="text-lg"></ion-icon>
                                My Account
                            </div>
                        </a>
                        <hr/>
                        <a asp-controller="Authentication" asp-action="Logout">
                            <div class="flex items-center gap-2.5 hover:bg-secondery p-2 px-2.5 rounded-md">
                                <ion-icon name="exit-outline" class="text-lg"></ion-icon>
                                Log Out

                            </div>
                        </a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>